/**
 * TEST-LEDGER.md generator — from vitest JSON output, never hand-edited
 * (a hand-edited number is a lie waiting to be believed). Runs the unit +
 * infra suites; integration numbers come from the last `make test-int` run
 * only when LocalStack is up (marked accordingly).
 */

import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

interface VitestJson {
  testResults: Array<{ name: string; assertionResults: Array<{ status: string }> }>;
}

const run = (args: string[]): VitestJson => {
  try {
    const out = execFileSync('npx', ['vitest', 'run', ...args, '--reporter=json'], {
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
    });
    return JSON.parse(out.slice(out.indexOf('{'))) as VitestJson;
  } catch (err) {
    const out = (err as { stdout?: string }).stdout ?? '';
    return JSON.parse(out.slice(out.indexOf('{'))) as VitestJson;
  }
};

const MILESTONES: Record<string, { milestone: string; tags: string }> = {
  'ping.test.ts': { milestone: 'M1', tags: '[HEALTH]' },
  'send-ott.test.ts': { milestone: 'M1', tags: '[AUTH-OTT]' },
  'verify-email.test.ts': { milestone: 'M1', tags: '[AUTH-OTT]' },
  'srp-math.test.ts': { milestone: 'M1', tags: '[AUTH-SRP]' },
  'srp-endpoints.test.ts': { milestone: 'M1', tags: '[AUTH-SRP]' },
  'account.test.ts': { milestone: 'M2', tags: '[KEYS] [ACCOUNT]' },
  'account-extras.test.ts': { milestone: 'M7', tags: '[ACCOUNT] completeness' },
  'upload.test.ts': { milestone: 'M3', tags: '[UPLOAD]' },
  'upload-v2.test.ts': { milestone: 'M3/M5', tags: '[UPLOAD] V2 (gate finding D26)' },
  'file-read.test.ts': { milestone: 'M3', tags: '[FILE-READ]' },
  'file-meta.test.ts': { milestone: 'M4', tags: '[FILE-META]' },
  'collections.test.ts': { milestone: 'M4', tags: '[COLLECTIONS] [SYNC]' },
  'trash.test.ts': { milestone: 'M4', tags: '[TRASH] + M4 gate' },
  'trash-purge.test.ts': { milestone: 'M4', tags: '[TRASH] cron' },
  'trash-origin.test.ts': { milestone: 'M4/M5', tags: '[TRASH] origin collection (gate finding D28)' },
  'entity.test.ts': { milestone: 'M5', tags: '[ENTITY]' },
  'stubs.test.ts': { milestone: 'M5', tags: '[CONFIG/BILLING/PUSH/BONUS-STUB]' },
  'social-stubs.test.ts': { milestone: 'M5', tags: 'social probes (gate finding D27)' },
  'cors.test.ts': { milestone: 'M5', tags: 'CORS preflight (gate finding D29)' },
  'subscription.test.ts': { milestone: 'M5', tags: '[BILLING] free-sub determinism (gate finding D30)' },
  'auth-token.test.ts': { milestone: 'M5', tags: 'query-param auth (gate finding D32)' },
  'totp.test.ts': { milestone: 'M5', tags: '[AUTH-2FA] TOTP math (RFC 6238)' },
  'two-factor.test.ts': { milestone: 'M5', tags: '[AUTH-2FA] TOTP flow (gate finding D36)' },
  'file-data.test.ts': { milestone: 'M6', tags: '[FILE-DATA]' },
  'lifecycle.test.ts': { milestone: 'M7', tags: 'infra guards' },
  'web.test.ts': { milestone: 'P3-F', tags: 'infra guards: albums web hosting (D52)' },
  'e2e.int.test.ts': { milestone: 'M1/M3', tags: 'integration (LocalStack)' },
  'db-counters.test.ts': { milestone: 'SEC', tags: 'F0 race-free capped counter (security review)' },
  'origin-lock.test.ts': { milestone: 'SEC', tags: 'origin lock (finding 4, D43)' },
  'presign-expiry.test.ts': { milestone: 'SEC', tags: 'presign expiry split (finding 5, D44)' },
  'db-transact.test.ts': { milestone: 'P3-A', tags: 'transactWrite atomicity + 100-op cap (D48)' },
  'sharing.test.ts': { milestone: 'P3-A', tags: '[SHARING] dual-write + link rows (D48)' },
  'invites.test.ts': { milestone: 'H1', tags: '[INVITES] [QUOTA] invite gating + per-user storage (D54)' },
};

const rows: string[] = [];
let total = 0;
let passed = 0;

const collect = (json: VitestJson) => {
  for (const file of json.testResults) {
    const base = file.name.split('/').at(-1)!;
    const info = MILESTONES[base] ?? { milestone: '?', tags: '?' };
    const pass = file.assertionResults.filter((a) => a.status === 'passed').length;
    const count = file.assertionResults.length;
    total += count;
    passed += pass;
    rows.push(`| ${base} | ${info.tags} | ${info.milestone} | ${count} | ${pass} | ${pass === count ? '✅' : '❌'} |`);
  }
};

collect(run(['test/unit']));
collect(run(['test/infra']));

// Probe LocalStack first: vitest "runs" the integration suite either way and
// a down stack would collect as failures — a lie the try/catch below never
// caught (run() swallows the non-zero exit and parses the JSON anyway).
const LOCALSTACK = process.env.AWS_ENDPOINT_URL ?? 'http://127.0.0.1:4567';
const localstackUp = await fetch(`${LOCALSTACK}/_localstack/health`)
  .then((r) => r.ok)
  .catch(() => false);

let intNote = 'not run (LocalStack down) — run `make up && make test-int && make ledger`';
if (localstackUp) {
  try {
    collect(run(['test/integration']));
    intNote = 'included';
  } catch {
    /* LocalStack not running */
  }
}

rows.sort();

const doc = `# TEST-LEDGER — generated by \`make ledger\`, never hand-edited

Integration suite: ${intNote}.
Oracle capture-parity: **pending** (no capture run yet — DECISIONS.md D2).

| Suite file | Tags | Milestone | Scenarios | Passing | |
|---|---|---|---|---|---|
${rows.join('\n')}

**Total: ${passed}/${total} passing.** CI must fail if any implemented endpoint is below 100%.
`;

writeFileSync(new URL('../TEST-LEDGER.md', import.meta.url), doc);
console.log(`TEST-LEDGER.md written: ${passed}/${total}`);
